version: '3.1'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    restart: always             # run as a service  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@beedatamyanmar.com
      - PGADMIN_DEFAULT_PASSWORD=p@ssw0rd
    ports:
      - 5050:80
  odoo15:
    image: nyizin/odoo_pyaekaungkyaw:1.0 #odoo:11.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    tty: true
#    command: odoo -u all -d FM_New_Db
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module

    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always 
volumes:
  odoo-web-data:
